CREATE TABLE billing_event_templates (
    id                              BIGSERIAL PRIMARY KEY,
    name                            VARCHAR(200)   NOT NULL,
    customer_number                 VARCHAR(9),
    contract_id                     BIGINT,
    product_id                      BIGINT,
    waste_fee_price                 NUMERIC(19,4),
    transport_fee_price             NUMERIC(19,4),
    eco_fee_price                   NUMERIC(19,4),
    quantity                        NUMERIC(19,4),
    weight                          NUMERIC(19,4),
    vehicle_id                      VARCHAR(50),
    driver_id                       VARCHAR(50),
    location_id                     VARCHAR(100),
    municipality_id                 VARCHAR(100),
    comments                        VARCHAR(2000),
    contractor                      VARCHAR(200),
    direction                       VARCHAR(20),
    shared_service_group_percentage NUMERIC(7,4),
    waste_type                      VARCHAR(100),
    receiving_site                  VARCHAR(200),
    created_by                      VARCHAR(255),
    created_at                      TIMESTAMP WITH TIME ZONE,
    last_modified_by                VARCHAR(255),
    last_modified_at                TIMESTAMP WITH TIME ZONE
);
